MY_APPS =  [
    'django.contrib.sites', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'django_markdown',
    'student',
    'contact',
    'Article',    
    'bootstrap3',
    #'oauth2_provider',
   #'corsheaders',
    #'bootstrapform',
    'bootstrap3_datetime',
    'sorl.thumbnail',   
	'pagedown',         
    
 ]
