# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:36
from __future__ import unicode_literals

import Feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, validators=[Feedback.models.validate_name])),
                ('Title', models.CharField(max_length=3)),
                ('Subject', models.CharField(max_length=100, validators=[Feedback.models.validate_name])),
                ('Message', models.CharField(max_length=1002, validators=[Feedback.models.validate_len])),
            ],
        ),
    ]
