# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
                ('count', django.db.models.manager.Manager()),
            ],
        ),
    ]
