# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20160713_1211'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='Date',
            field=models.DateField(default='2015-02-27', verbose_name=datetime.datetime(2016, 7, 19, 16, 56, 12, 115083, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
