# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:57
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=10, validators=[Article.models.valid_name])),
                ('content', models.CharField(max_length=20000, validators=[Article.models.valid_content])),
                ('publ_date', models.DateField()),
            ],
        ),
    ]
