# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 11:42
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=20, validators=[Article.models.valid_name])),
                ('comment_date', models.DateField()),
                ('comment_content', models.CharField(max_length=400, validators=[Article.models.valid_comment])),
            ],
        ),
        migrations.CreateModel(
            name='New_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=10, validators=[Article.models.valid_name])),
                ('article_name', models.CharField(max_length=30, validators=[Article.models.valid_name])),
                ('content', models.CharField(max_length=20000, validators=[Article.models.valid_content])),
                ('publ_date', models.DateField(verbose_name=b'Publication Date')),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article_Comment')),
            ],
        ),
    ]
