# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 11:47
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_article',
            name='article_comment',
        ),
        migrations.AddField(
            model_name='article_comment',
            name='article_comment_key',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Article.New_Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_content',
            field=models.CharField(blank=True, max_length=400, validators=[Article.models.valid_comment]),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_name',
            field=models.CharField(blank=True, max_length=20, validators=[Article.models.valid_name]),
        ),
    ]
