# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:02
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20160923_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_comment',
            name='article_comment_key',
        ),
        migrations.AddField(
            model_name='new_article',
            name='article_comment_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Article.New_Article'),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_name',
            field=models.CharField(blank=True, max_length=20, validators=[Article.models.valid_name], verbose_name=b'Your Name'),
        ),
    ]
