# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20160709_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewArticle',
            new_name='New_Article',
        ),
    ]
