# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:43
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20160709_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_article',
            name='article_name',
            field=models.CharField(default='Power of DJango', max_length=30, validators=[Article.models.valid_name]),
            preserve_default=False,
        ),
    ]
