# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20160923_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_article',
            name='slug',
            field=models.SlugField(default='Power of Django'),
            preserve_default=False,
        ),
    ]
