# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_new_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
