# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_new_article_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_article',
            name='publ_date',
            field=models.DateField(verbose_name=b'Publication Date'),
        ),
    ]
