# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_auto_20160712_1409'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='new_article',
            managers=[
                ('author', django.db.models.manager.Manager()),
            ],
        ),
    ]
