# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_remove_new_article_article_comment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='object_match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Article.New_Article'),
            preserve_default=False,
        ),
    ]
