# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_article_comment_object_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_comment',
            name='object_match',
        ),
        migrations.AddField(
            model_name='new_article',
            name='object_match',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Article.Article_Comment'),
            preserve_default=False,
        ),
    ]
