# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20160924_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
