# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_article_comment_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_article',
            name='object_match',
        ),
    ]
