# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 13:16
from __future__ import unicode_literals

import Article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0011_auto_20160925_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comment',
            name='comment_content',
            field=models.CharField(max_length=400, validators=[Article.models.valid_comment]),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_name',
            field=models.CharField(max_length=20, validators=[Article.models.valid_name], verbose_name=b'Your Name'),
        ),
    ]
