# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0012_auto_20160926_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
