# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0013_article_comment_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='article_comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article_Comment'),
        ),
    ]
