# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0014_auto_20160926_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reply',
            new_name='reply_comment',
        ),
    ]
